name: publish-release.yml

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Dummy: "DUMMY"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild /t:Restore /p:Configuration=Release

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild /p:Configuration=Release

    - name: Install crates
      run: |
        cargo install --git https://github.com/mass10/r-gh-create-release --branch main

    - name: Create a new release
      run: |
        r-gh-create-release `
          --file bin\Release\net6.0\AWSSDK.Core.dll `
          --file bin\Release\net6.0\AWSSDK.S3.dll `
          --file bin\Release\net6.0\dotnets3.dll `
          --file bin\Release\net6.0\dotnets3.exe `
          --file bin\Release\net6.0\dotnets3.runtimeconfig.json `
          --file bin\Release\net6.0\Newtonsoft.Json.dll

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
